apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: learner-report
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: learner-report
      component: frontend
  template:
    metadata:
      labels:
        app: learner-report
        component: frontend
    spec:
      containers:
      - name: frontend
        image: learner-report-frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_BASE_URL
          value: "http://backend-service:3000"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
