apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: learner-report
    component: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
