apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: learner-report
    component: backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: learner-report
      component: backend
  template:
    metadata:
      labels:
        app: learner-report
        component: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
        imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/{{ .Values.mongodb.database }}"
        resources:
          {{- toYaml .Values.resources.backend | nindent 10 }}
