apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: learner-report
    component: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
