# Default values for learner-report chart

replicaCount:
  frontend: 3
  backend: 3
  mongodb: 1

image:
  frontend:
    repository: a7i0/learner-report-frontend
    tag: latest
    pullPolicy: IfNotPresent
  backend:
    repository: a7i0/learner-report-backend
    tag: latest
    pullPolicy: IfNotPresent
  mongodb:
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent

service:
  frontend:
    type: LoadBalancer
    port: 80
    targetPort: 3000
  backend:
    type: ClusterIP
    port: 3000
  mongodb:
    type: ClusterIP
    port: 27017

resources:
  frontend:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
  backend:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
  mongodb:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"

mongodb:
  database: "learner-report"
